
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Leo
 */
public class Vocales extends javax.swing.JFrame {

    /**
     * Creates new form Vocales
     */
    public Vocales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTema = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        txtCadena = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        txtAlrevez = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTema.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTema.setText("Practica:");
        jPanel1.add(lblTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 110, 30));

        lblFrase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFrase.setText("FRASE:");
        jPanel1.add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 82, -1, -1));

        txtCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadenaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCadena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 370, 30));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        txtAlrevez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlrevezActionPerformed(evt);
            }
        });
        jPanel1.add(txtAlrevez, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 370, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadenaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       
        contadorVocales();
        contadorPalabras();
         oracionAlReves();
        reemplazarLetras();
        


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtAlrevezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlrevezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlrevezActionPerformed
    public void contadorVocales() {
                String frase =  txtCadena.getText();


        int A = 0, E = 0, I = 0, O = 0, U = 0;

        for (int i = 0; i < frase.length(); i++) {         
            char caracter = frase.charAt(i);

            if (Character.toString(caracter).equalsIgnoreCase("a")) {
                A++;
            } else if (Character.toString(caracter).equalsIgnoreCase("e")) {
                E++;
            } else if (Character.toString(caracter).equalsIgnoreCase("i")) {
                I++;
            } else if (Character.toString(caracter).equalsIgnoreCase("o")) {
                O++;
            } else if (Character.toString(caracter).equalsIgnoreCase("u")) {
                U++;
            }
        }

        JOptionPane.showMessageDialog(rootPane, "Hay " + A + " Voclaes A");
        JOptionPane.showMessageDialog(rootPane, "Hay " + E + " Voclaes E");
        JOptionPane.showMessageDialog(rootPane, "Hay " + I + " Voclaes I");
        JOptionPane.showMessageDialog(rootPane, "Hay " + O + " Voclaes O");
        JOptionPane.showMessageDialog(rootPane, "Hay " + U + " Voclaes U");

    }
    
 public void contadorPalabras() {
        int cont = 0;
        
        String frase =  txtCadena.getText();

        for (int i = 0; i < frase.length(); i++) { //longitud frase.length
            char caracter = frase.charAt(i);

            if (Character.isWhitespace(caracter) || i == frase.length() - 1) {  //// Verifica si el caracter es un espacio en blanco o el final de la cadena
                cont++;
            }
        }

        JOptionPane.showMessageDialog(rootPane, "Número de palabras: " + cont);
    }
   
 public void reemplazarLetras() {
           String frase =  txtCadena.getText();

    
    char[] nuevaF = new char[frase.length()];

    for (int i = 0; i < frase.length(); i++) {
        char caracter = frase.charAt(i); //Se obtiene el carácter en la posición actual de la cadena

        if (caracter == 'o') {
            nuevaF[i] = '$';
        } else if (caracter == 'a') {
            nuevaF[i] = '@';
        } else {
            nuevaF[i] = caracter;
        }
    }
 String frase2 = new String(nuevaF);
   txtCadena.setText(frase2);
 }

 public void oracionAlReves() {
    
            String Original =  txtCadena.getText();

    char[] caracteres = Original.toCharArray();


    char[] fraseA = new char[caracteres.length];
    for (int i = 0; i < caracteres.length; i++) {
        fraseA[i] = caracteres[caracteres.length - 1 - i];
    }
    
     String frase2 = new String(fraseA);
     txtAlrevez.setText(frase2);


    
}
   


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vocales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblTema;
    private javax.swing.JTextField txtAlrevez;
    private javax.swing.JTextField txtCadena;
    // End of variables declaration//GEN-END:variables
}
